In [1]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/DAT490 BitWizards/Data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import os

In [3]:
# List all files in the directory
files = os.listdir(file_path)
file1 = 'test_identity.csv'
file2='test_transaction_merged.csv'
file3='train_identity.csv'
file4='train_transaction_merged.csv'

In [4]:
# Read your files into dataframes
df1 = pd.read_csv(os.path.join(file_path, file1))
df2 = pd.read_csv(os.path.join(file_path, file2))
df3 = pd.read_csv(os.path.join(file_path, file3))
df4 = pd.read_csv(os.path.join(file_path, file4))

# Merge test files
test_set = pd.merge(df1, df2, on='TransactionID', how='inner')

# Merge train files
train_set = pd.merge(df3, df4, on='TransactionID', how='inner')

In [11]:
print(df4.shape)
print(df3.shape)

(140232, 434)
(144233, 41)

In [6]:
# Check the dimensions of the dataframes
print("Train Set Dimensions: ", train_set.shape)
print("Test Set Dimensions: ", test_set.shape)

# Get a quick overview of the datasets
print("\nTrain Set Overview:")
print(train_set.info())
print("\nTest Set Overview:")
print(test_set.info())

# Display the first few rows of the dataframes
print("\nTrain Set First Few Rows:")
print(train_set.head())
print("\nTest Set First Few Rows:")
print(test_set.head())

# Display the summary statistics of the dataframes
print("\nTrain Set Summary Statistics:")
print(train_set.describe())
print("\nTest Set Summary Statistics:")
print(test_set.describe())

# Check for missing values in the dataframes
print("\nTrain Set Missing Values:")
print(train_set.isnull().sum())
print("\nTest Set Missing Values:")
print(test_set.isnull().sum())

Train Set Dimensions:  (140232, 474)
Test Set Dimensions:  (136607, 473)

Train Set Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140232 entries, 0 to 140231
Columns: 474 entries, TransactionID to DeviceInfo_y
dtypes: float64(430), int64(4), object(40)
memory usage: 507.1+ MB
None

Test Set Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136607 entries, 0 to 136606
Columns: 473 entries, TransactionID to DeviceInfo_y
dtypes: float64(430), int64(3), object(40)
memory usage: 493.0+ MB
None

Train Set First Few Rows:
   TransactionID  id_01_x   id_02_x  id_03_x  id_04_x  id_05_x  id_06_x  \
0        2987004      0.0   70787.0      NaN      NaN      NaN      NaN
1        2987008     -5.0   98945.0      NaN      NaN      0.0     -5.0
2        2987010     -5.0  191631.0      0.0      0.0      0.0      0.0
3        2987011     -5.0  221832.0      NaN      NaN      0.0     -6.0
4        2987016      0.0    7460.0      0.0      0.0      1.0      0.0

   id_07_x  id_08_x  id_09_x  ...              id_31_y  id_32_y    id_33_y  \
0      NaN      NaN      NaN  ...  samsung browser 6.2     32.0  2220x1080
1      NaN      NaN      NaN  ...   mobile safari 11.0     32.0   1334x750
2      NaN      NaN      0.0  ...          chrome 62.0      NaN        NaN
3      NaN      NaN      NaN  ...          chrome 62.0      NaN        NaN
4      NaN      NaN      0.0  ...          chrome 62.0     24.0   1280x800

          id_34_y  id_35_y id_36_y id_37_y  id_38_y  DeviceType_y  \
0  match_status:2        T       F       T        T        mobile
1  match_status:1        T       F       F        T        mobile
2             NaN        F       F       T        T       desktop
3             NaN        F       F       T        T       desktop
4  match_status:2        T       F       T        T       desktop

                    DeviceInfo_y
0  SAMSUNG SM-G892A Build/NRD90M
1                     iOS Device
2                        Windows
3                            NaN
4                          MacOS

[5 rows x 474 columns]

Test Set First Few Rows:
   TransactionID  id-01     id-02  id-03  id-04  id-05  id-06  id-07  id-08  \
0        3663586  -45.0  280290.0    NaN    NaN    0.0    0.0    NaN    NaN
1        3663588    0.0    3579.0    0.0    0.0    0.0    0.0    NaN    NaN
2        3663597   -5.0  185210.0    NaN    NaN    1.0    0.0    NaN    NaN
3        3663601  -45.0  252944.0    0.0    0.0    0.0    0.0    NaN    NaN
4        3663602  -95.0  328680.0    NaN    NaN    7.0  -33.0    NaN    NaN

   id-09  ...                    id_31  id_32     id_33           id_34  \
0    NaN  ...  chrome 67.0 for android    NaN       NaN             NaN
1    0.0  ...  chrome 67.0 for android   24.0  1280x720  match_status:2
2    NaN  ...       ie 11.0 for tablet    NaN       NaN             NaN
3    0.0  ...  chrome 67.0 for android    NaN       NaN             NaN
4    NaN  ...  chrome 67.0 for android    NaN       NaN             NaN

   id_35 id_36 id_37  id_38  DeviceType_y                 DeviceInfo_y
0      F     F     T      F        mobile  MYA-L13 Build/HUAWEIMYA-L13
1      T     F     T      T        mobile         LGLS676 Build/MXB48T
2      F     T     T      F       desktop                  Trident/7.0
3      F     F     T      F        mobile  MYA-L13 Build/HUAWEIMYA-L13
4      F     F     T      F        mobile         SM-G9650 Build/R16NW

[5 rows x 473 columns]

Train Set Summary Statistics:
       TransactionID        id_01_x        id_02_x       id_03_x  \
count   1.402320e+05  140232.000000  140232.000000  65847.000000
mean    3.235563e+06     -10.029501  175173.468659      0.060504
std     1.783011e+05      14.487836  159626.165147      0.600132
min     2.987004e+06    -100.000000       1.000000    -13.000000
25%     3.077223e+06     -10.000000   68390.500000      0.000000
50%     3.198074e+06      -5.000000  126169.000000      0.000000
75%     3.391758e+06      -5.000000  229105.250000      0.000000
max     3.577534e+06       0.000000  999595.000000     10.000000

            id_04_x        id_05_x        id_06_x      id_07_x      id_08_x  \
count  65847.000000  136572.000000  136572.000000  5149.000000  5149.000000
mean      -0.059274       1.615573      -6.688216    13.291319   -38.586327
std        0.703151       5.247565      16.464992    11.385839    26.096531
min      -28.000000     -72.000000    -100.000000   -46.000000  -100.000000
25%        0.000000       0.000000      -6.000000     5.000000   -48.000000
50%        0.000000       0.000000       0.000000    14.000000   -34.000000
75%        0.000000       1.000000       0.000000    22.000000   -23.000000
max        0.000000      52.000000       0.000000    61.000000     0.000000

            id_09_x  ...        id_17_y       id_18_y        id_19_y  \
count  74414.000000  ...  139074.000000  44971.000000  139023.000000
mean       0.091179  ...     189.457109     14.237820     353.186005
std        0.986411  ...      30.373509      1.562653     141.112319
min      -36.000000  ...     100.000000     10.000000     100.000000
25%        0.000000  ...     166.000000     13.000000     266.000000
50%        0.000000  ...     166.000000     15.000000     341.000000
75%        0.000000  ...     225.000000     15.000000     427.000000
max       25.000000  ...     229.000000     29.000000     671.000000

             id_20_y      id_21_y      id_22_y      id_24_y      id_25_y  \
count  138966.000000  5153.000000  5163.000000  4741.000000  5126.000000
mean      403.953874   368.414710    16.005036    12.802362   329.474834
std       152.127615   198.913748     6.901334     2.373012    97.429309
min       100.000000   100.000000    10.000000    11.000000   100.000000
25%       256.000000   252.000000    14.000000    11.000000   321.000000
50%       472.000000   252.000000    14.000000    11.000000   321.000000
75%       533.000000   487.000000    14.000000    15.000000   371.000000
max       661.000000   854.000000    44.000000    26.000000   548.000000

           id_26_y       id_32_y
count  5157.000000  77345.000000
mean    149.085515     26.512793
std      32.114308      3.739033
min     100.000000      0.000000
25%     119.000000     24.000000
50%     149.000000     24.000000
75%     169.000000     32.000000
max     216.000000     32.000000

[8 rows x 434 columns]

Test Set Summary Statistics:
       TransactionID          id-01          id-02         id-03  \
count   1.366070e+05  136607.000000  136607.000000  66333.000000
mean    3.973209e+06     -11.164662  193135.399064      0.053005
std     1.472530e+05      14.735098  182592.018833      0.685011
min     3.663586e+06    -100.000000       2.000000    -12.000000
25%     3.858446e+06     -10.000000   63874.500000      0.000000
50%     4.004514e+06      -5.000000  133618.000000      0.000000
75%     4.106003e+06      -5.000000  266319.000000      0.000000
max     4.170239e+06       0.000000  999869.000000     11.000000

              id-04          id-05          id-06        id-07        id-08  \
count  66333.000000  134456.000000  134456.000000  5057.000000  5057.000000
mean      -0.087649       1.242287      -6.804925    12.495551   -36.564959
std        0.841278       5.067705      15.925333    11.679801    25.541094
min      -19.000000     -81.000000    -100.000000   -41.000000  -100.000000
25%        0.000000       0.000000      -6.000000     3.000000   -46.000000
50%        0.000000       0.000000       0.000000    12.000000   -33.000000
75%        0.000000       1.000000       0.000000    21.000000   -23.000000
max        0.000000      52.000000       0.000000    59.000000     0.000000

              id-09  ...          id_17         id_18          id_19  \
count  74176.000000  ...  135671.000000  50735.000000  135611.000000
mean       0.076292  ...     191.123586     14.794028     350.110751
std        1.010569  ...      30.759569      2.308267     139.090331
min      -32.000000  ...     100.000000     11.000000     100.000000
25%        0.000000  ...     166.000000     13.000000     266.000000
50%        0.000000  ...     166.000000     15.000000     321.000000
75%        0.000000  ...     225.000000     15.000000     427.000000
max       16.000000  ...     228.000000     29.000000     670.000000

               id_20        id_21        id_22        id_24        id_25  \
count  135338.000000  5057.000000  5060.000000  4738.000000  5037.000000
mean      408.924714   507.855448    15.337352    13.167581   332.083184
std       158.971165   227.324264     5.619079     3.222812    86.350345
min       100.000000   100.000000    11.000000    10.000000   100.000000
25%       256.000000   252.000000    14.000000    11.000000   321.000000
50%       484.000000   576.000000    14.000000    11.000000   321.000000
75%       549.000000   711.000000    14.000000    15.000000   355.000000
max       660.000000   854.000000    44.000000    26.000000   549.000000

             id_26         id_32
count  5045.000000  70627.000000
mean    152.767096     26.219321
std      31.915380      3.601741
min     100.000000      8.000000
25%     137.000000     24.000000
50%     147.000000     24.000000
75%     182.000000     32.000000
max     216.000000     48.000000

[8 rows x 433 columns]

Train Set Missing Values:
TransactionID        0
id_01_x              0
id_02_x              0
id_03_x          74385
id_04_x          74385
                 ...
id_36_y              0
id_37_y              0
id_38_y              0
DeviceType_y         0
DeviceInfo_y     21910
Length: 474, dtype: int64

Test Set Missing Values:
TransactionID        0
id-01                0
id-02                0
id-03            70274
id-04            70274
                 ...
id_36                0
id_37                0
id_38                0
DeviceType_y         0
DeviceInfo_y     21611
Length: 473, dtype: int64

In [9]:
# display(train_set)
# pd.set_option('display.max_rows', None)
train_set[['P_emaildomain','R_emaildomain']].count()

P_emaildomain    127579
R_emaildomain    127417
dtype: int64

In [8]:
train_set['card1']

0          4497
1          2803
2         16496
3          4461
4          1790
          ...
140227    12019
140228     1214
140229     5096
140230     6019
140231     5812
Name: card1, Length: 140232, dtype: int64